name: '<ACTION NAME>'
description: '<ACTION DESCRIPTION>'

inputs:
  optional_input:
    description: '<INPUT DESCRIPTION>'
    required: false
    default: '<DEFAULT INPUT>'

outputs:
  optional_output:
    description: '<OUTPUT DESCRIPTION>'

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Get Node versiom from .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install --frozen-lockfile --offline
